bulk_update :package:: ["scripts/migrations/**"]
  - "scripts/migrations/**"
data:api :rabbit2:: ["api/**"]
  - "api/**"
data:browsers :earth_africa:: ["browsers/**"]
  - "browsers/**"
data:css :art::
  - "css/**"
data:html :page_facing_up::
  - "html/**"
data:http :mountain_cableway::
  - "http/**"
data:js :pager::
  - "javascript/**"
data:mathml :heavy_division_sign::
  - "mathml/**"
data:svg :paintbrush::
  - "svg/**"
data:wasm :mechanical_arm::
  - "webassembly/**"
data:webdriver :racing_car::
  - "webdriver/**"
data:webext :game_die::
  - "webextensions/**"
dependencies :chains::
  - "package-lock.json"
  - "package.json"
docs :writing_hand::
  - "**/*.md"
infra :building_construction:: - [".*"]
  - ".*"
  - "/*.js"
  - "*.ts"
  - "**/*.d.ts"
  - "/index.js"
  - "LICENSE"
  - "package*"
  - "utils/**"
  - ".github/**"
  - ".husky/**"
  - ".vscode/**"
linter :house_with_garden::
  - "test/**"
scripts :scroll::
  - "scripts/**"
schema :gear:: ["schemas/**"]
  - "schemas/**"
